MvcKutuphane/Controllers/AyarlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;

namespace MvcKutuphane.Controllers
{
    public class AyarlarController : Controller
    {
        // GET: Ayarlar

        DBKUTUPHANEEntities DbModel = new DBKUTUPHANEEntities();
        public ActionResult ayarlar()
        {
            var kullanicilar = DbModel.TBLADMIN.ToList();
            return View(kullanicilar);
        }

        public ActionResult ayarlar2()
        {
            var kullanicilar = DbModel.TBLADMIN.ToList();
            return View(kullanicilar);
        }

        [HttpGet]
        public ActionResult YeniAdmin()
        {
            
            return View();
        }


        [HttpPost]
        public ActionResult YeniAdmin (TBLADMIN t)
        {
            DbModel.TBLADMIN.Add(t);
            DbModel.SaveChanges();
            return RedirectToAction("ayarlar2");
        }

        public ActionResult AdminSil(int id)
        {
            var admin = DbModel.TBLADMIN.Find(id);
            DbModel.TBLADMIN.Remove(admin);
            DbModel.SaveChanges();
            return RedirectToAction("ayarlar2");
        }

        [HttpGet]
        public ActionResult AdminGuncelle(int id)
        {
            var admin = DbModel.TBLADMIN.Find(id);
            return View(admin);
        }

        [HttpPost]
        public ActionResult AdminGuncelle(TBLADMIN prmt)
        {
            var admin = DbModel.TBLADMIN.Find(prmt.ADMINID);
            admin.KULLANICI = prmt.KULLANICI;
            admin.SIFRE = prmt.SIFRE;
            admin.YETKI = prmt.YETKI;
            DbModel.SaveChanges();
            return RedirectToAction("ayarlar2");
        }


    }
}

MvcKutuphane/Views/Ayarlar/AdminGuncelle.cshtml
@model MvcKutuphane.Models.Entity.TBLADMIN
@{
    ViewBag.Title = "AdminGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AdminGuncelle", "Ayarlar", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <label>KAdmin ID :</label>
        @Html.TextBoxFor(k => k.ADMINID, new { @class = "form-control" })
        <br />

        <label>Kullanıcı Adı:</label>
        @Html.TextBoxFor(k => k.KULLANICI, new { @class = "form-control" })

        <label>Şifre:</label>
        @Html.TextBoxFor(k => k.SIFRE, new { @class = "form-control" })

        <label>Yetki:</label>
        @Html.TextBoxFor(k => k.YETKI, new { @class = "form-control" })

    </div>
    <div>
        <button class="btn btn-info">Güncelle</button>
    </div>

}

MvcKutuphane/Views/Ayarlar/ayarlar.cshtml
@{
    ViewBag.Title = "ayarlar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Projects</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Projects</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Kullanıcı Adı
                            </th>
                            <th style="width: 10%">
                                Avatar
                            </th>
                            <th style="width: 8%" class="text-center">
                                Yetki
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                #
                            </td>
                            <td>
                                <a>
                                    AdminLTE v3
                                </a>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <img alt="Avatar" class="table-avatar" src="/AdminLTE-3.0.4//dist/img/avatar.png">
                                    </li>
                                </ul>
                            </td>
                            <td class="project-state">
                                <span class="badge badge-success">Success</span>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-info btn-sm" href="#">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Düzenle
                                </a>
                                <a class="btn btn-danger btn-sm" href="#">
                                    <i class="fas fa-trash">
                                    </i>
                                    Sil
                                </a>
                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
</body>
</html>

MvcKutuphane/Views/Ayarlar/ayarlar2.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLADMIN>
@{
    ViewBag.Title = "ayarlar2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Kullanıcı</th>
        <th>Yetki</th>
        <th>Düzenle</th>
        <th>Sil</th>
        

    </tr>
    @foreach (var item in Model)
    {
    <tr>
       <td>@item.ADMINID</td>
       <td>@item.KULLANICI</td>
       <td>@item.YETKI</td>
       


        <td>
            <a class="btn btn-info btn-sm" href="/Ayarlar/AdminGuncelle/@item.ADMINID">
                <i class="fas fa-pencil-alt">
                </i>
                Düzenle
            </a>
            </td>
        <td>
            <a class="btn btn-danger btn-sm" href="/Ayarlar/AdminSil/@item.ADMINID">
                <i class="fas fa-trash">
                </i>
                Sil
            </a>
        </td>
    </tr>

    }

</table>
<br />

<button class="btn btn-primary" data-toggle="modal" data-target="#Modal1">Yeni Admin Ekle</button>

<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Admin Ekleme Paneli</h2>
            </div>
            <form method="post" action="/Ayarlar/YeniAdmin/">
                <div class="modal-body">
                    <label>Kullanıcı Adı</label>
                    <input type="text" name="KULLANICI" class="form-control" />
                    <br />
                    <label>Şifre</label>
                    <input type="text" name="SIFRE" class="form-control" />
                    <br />
                    <label>Yetki</label>
                    <input type="text" name="YETKI" class="form-control" />
                    <br />
                    <button class="btn btn-info">Kaydet</button>
                </div>
            </form>
        </div>
    </div>

</div>