MvcKutuphane/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using MvcKutuphane.Models.Entity;

namespace MvcKutuphane.Controllers
{
    public class KitapController : Controller
    {
        // GET: Kitap

        DBKUTUPHANEEntities DbModel = new DBKUTUPHANEEntities();
        public ActionResult kitapListele(string search, int ? page)
        {
            return View(DbModel.TBLKITAP.Where(x => x.KITAPAD.Contains(search) || search == null).ToList().ToPagedList(page ?? 1, 5));

           
           
        }

        [HttpGet]
        public ActionResult kitapEkle()
        {
            List<SelectListItem> kitapDeger = (from i in DbModel.TBLKATEGORI.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD,
                                               Value = i.KATEGORIID.ToString()
                                           }).ToList();
            ViewBag.ktpDgr = kitapDeger;

            List<SelectListItem> yazarDeger = (from i in DbModel.TBLYAZAR.ToList()
                                                select new SelectListItem
                                                {
                                                    Text = i.AD +' '+i.SOYAD,
                                                    Value = i.YAZARID.ToString()
                                                }).ToList();
            ViewBag.yzrDgr = yazarDeger;
            return View();

        }

        [HttpPost]
        public ActionResult kitapEkle(TBLKITAP kitap)
        {
            var ktg = DbModel.TBLKATEGORI.Where(k => k.KATEGORIID ==kitap.TBLKATEGORI.KATEGORIID).FirstOrDefault();
            var yzr = DbModel.TBLYAZAR.Where(y => y.YAZARID == kitap.TBLYAZAR.YAZARID).FirstOrDefault();
            kitap.TBLKATEGORI = ktg;
            kitap.TBLYAZAR = yzr;
            DbModel.TBLKITAP.Add(kitap);
            DbModel.SaveChanges();
            return RedirectToAction("kitapListele");
        }

        public ActionResult kitapSil(int id)
        {
            var kitap = DbModel.TBLKITAP.Find(id);
            DbModel.TBLKITAP.Remove(kitap);
            DbModel.SaveChanges();
            return RedirectToAction("kitaplistele");
        }

        public ActionResult kitapGetir(int id)
        {
            var kitap = DbModel.TBLKITAP.Find(id);

            List<SelectListItem> kitapDeger = (from i in DbModel.TBLKATEGORI.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = i.AD,
                                                   Value = i.KATEGORIID.ToString()
                                               }).ToList();
            ViewBag.ktpDgr = kitapDeger;

            List<SelectListItem> yazarDeger = (from i in DbModel.TBLYAZAR.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = i.AD + ' ' + i.SOYAD,
                                                   Value = i.YAZARID.ToString()
                                               }).ToList();
            ViewBag.yzrDgr = yazarDeger;

            return View(kitap);

        }


        public ActionResult kitapGuncelle(TBLKITAP prmt) 
        {
            var kitap = DbModel.TBLKITAP.Find(prmt.KITAPID);
            kitap.KITAPAD = prmt.KITAPAD;
            kitap.BASIMYIL = prmt.BASIMYIL;
            kitap.SAYFA = prmt.SAYFA;
            kitap.YAYINEVİ = prmt.YAYINEVİ;
            kitap.DURUM = true;
            var ktg = DbModel.TBLKATEGORI.Where(k => k.KATEGORIID == prmt.TBLKATEGORI.KATEGORIID).FirstOrDefault();

            var yzr = DbModel.TBLYAZAR.Where(y=> y.YAZARID== prmt.TBLYAZAR.YAZARID).FirstOrDefault();

            kitap.KATEGORI = ktg.KATEGORIID;
            kitap.YAZAR = yzr.YAZARID;
            DbModel.SaveChanges();

            return RedirectToAction("kitapListele");
        }

    }
}

MvcKutuphane/Views/Kitap/kitapEkle.cshtml
@model MvcKutuphane.Models.Entity.TBLKITAP
@{
    ViewBag.Title = "kitapEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("kitapEkle", "Kitap", FormMethod.Post))
{
 
    <div class="marginBottom" style="margin-top:15px">
        <div class="form-group">
            <label>Kitap AD</label>
            @Html.TextBoxFor(k => k.KITAPAD, new { @class = "form-control" })
        </div>
    </div>

    <div class="marginBottom" style="margin-top:15px">
        <div class="form-group">
            <label>Kategori</label>
            @Html.DropDownListFor(k => k.TBLKATEGORI.KATEGORIID, (List<SelectListItem>)ViewBag.ktpDgr, new { @class = "form-control" })
        </div>
    </div>

    <div class="marginBottom" style="margin-top:15px">
        <div class="form-group">
            <label>Yazar</label>
            @Html.DropDownListFor(k => k.TBLYAZAR.YAZARID, (List<SelectListItem>)ViewBag.yzrDgr, new { @class = "form-control" })
        </div>
    </div>

    <div class="marginBottom" style="margin-top:15px">
        <div class="form-group">
            <label>Sayfa Sayısı</label>
            @Html.TextBoxFor(k => k.SAYFA, new { @class = "form-control" })
        </div>
    </div>

    <div class="marginBottom" style="margin-top:15px">
        <div class="form-group">
            <label>Basım Yılı</label>
            @Html.TextBoxFor(k => k.BASIMYIL, new { @class = "form-control" })
        </div>
    </div>

    <div class="marginBottom" style="margin-top:15px">
        <div class="form-group">
            <label>Yayınevi</label>
            @Html.TextBoxFor(k => k.YAYINEVİ, new { @class = "form-control" })
        </div>
    </div>

    <input type="hidden" name="Durum" value="true"/>
    <button class="btn btn-warning" onclick="return confirm('Kitap eklemek istiyor musunuz?')">Kitap Ekle</button>

}

MvcKutuphane/Views/Kitap/kitapGetir.cshtml
@model MvcKutuphane.Models.Entity.TBLKITAP
@{
    ViewBag.Title = "kitapGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("kitapGuncelle", "Kitap", FormMethod.Post))
{


    <div class="marginBottom" style="margin-top:15px">
        <div class="form-group">
            <label>Kitap ID</label>
            @Html.TextBoxFor(k => k.KITAPID, new { @class = "form-control" })
        </div>
    </div>
    <div class="marginBottom">
        <div class="form-group">
            <label>Kitap Ad</label>
            @Html.TextBoxFor(k => k.KITAPAD, new { @class = "form-control" })
        </div>
    </div>

    <div class="marginBottom">
        <div class="form-group">
            <label>Kategori</label>
            @Html.DropDownListFor(k => k.TBLKATEGORI.KATEGORIID, (List<SelectListItem>)ViewBag.ktpDgr, new { @class = "form-control" })
        </div>
    </div>
    <div class="marginBottom">
        <div class="form-group">
            <label>Yazarı</label>
            @Html.DropDownListFor(k => k.TBLYAZAR.YAZARID, (List<SelectListItem>)ViewBag.yzrDgr, new { @class = "form-control" })
        </div>
    </div>

    <div class="marginBottom">
        <div class="form-group">
            <label>Basım Yılı</label>
            @Html.TextBoxFor(k => k.BASIMYIL, new { @class = "form-control" })
        </div>
    </div>

    <div class="marginBottom">
        <div class="form-group">
            <label>Yayınevi</label>
            @Html.TextBoxFor(k => k.YAYINEVİ, new { @class = "form-control" })
        </div>
    </div>

    <div class="marginBottom">
        <div class="form-group">
            <label>Sayfa Sayısı</label>
            @Html.TextBoxFor(k => k.SAYFA, new { @class = "form-control" })
        </div>
    </div>



    <button class="btn btn-warning" onclick="return confirm('Güncellemek istiyor musunuz?')">Kitap Bilgilerini Güncelle</button>
    
}

MvcKutuphane/Views/Kitap/kitapListele.cshtml
@using MvcKutuphane.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TBLKITAP>
@{
    ViewBag.Title = "kitapListele";
    Layout = "~/Views/Shared/_Layout.cshtml";

    string renk = "";
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>


<h2>Kitaplar</h2>

@using (Html.BeginForm("kitapListele", "Kitap", FormMethod.Get))
{
    <div style="margin-bottom:15px; margin-top:15px">
        <b>Kitap ara:</b> @Html.TextBox("search")
        <input type="submit" value="Ara" />

    </div>
}
<table class="table">
    <tr>
        <th>Kitap ID</th>
        <th>Kitap Ad</th>
        <th>Kategori</th>
        <th>Yazar</th>
        <th>Basım Yılı</th>
        <th>Yayınevi</th>
        <th>Sayfa</th>
        <th>Durum</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var kitap in Model)
    {

        if (kitap.DURUM == false)
        {
            renk = "text-bg-danger";
        }

        if (kitap.DURUM == true)
        {
            renk = "text-bg-primary";
        }



        <tr>
            <td>@kitap.KITAPID</td>
            <td>@kitap.KITAPAD</td>
            <td>@kitap.TBLKATEGORI.AD</td>
            <td>@kitap.TBLYAZAR.AD @kitap.TBLYAZAR.SOYAD</td>
            <td>@kitap.BASIMYIL</td>
            <td>@kitap.YAYINEVİ</td>
            <td>@kitap.SAYFA</td>
            <td class="@renk">@kitap.DURUM</td>
            <td>@Html.ActionLink("Sil", "kitapSil", new { id = kitap.KITAPID }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek İstiyor Musunuz?')" })</td>
            <td>@Html.ActionLink("Güncelle", "kitapGetir", new { id = kitap.KITAPID }, new { @class = "btn btn-success" })</td>
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model, page => Url.Action("KitapListele", new { page }))
<a class="btn btn-primary" href="/Kitap/kitapEkle/">Yeni Kitap Ekle</a>